defaultPortal: moon-site
portals:
  - name: moon-site
    portalId: 20072261
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNaUgaGaLxIJAA0AAAAA4A0DGMWOyQkghKHcCyju6QwyGQDw6X-J8Q1Jqxsx6BqSoJlJ9FA1lV-uG5M6KAAABEEAAAB4AAAAAAAAAAAAAAAAAAAABAAAwAcA_v8xPAAABgAAAGBCGQDw6X-JmChd_jK9WpO4_rznxLp2Uu1w6BtKA25hMQ
        expiresAt: '2021-05-25T15:24:10.204Z'
    personalAccessKey: >-
      CiQ1YWI5MjE3ZC0yOTQ4LTQ5OTYtOWZjMi1jOTNhNmQ2YmU0ZjgQxY7JCRiEodwLKhkABeaRgsMOYTMgt4IqEpzJnYvzE-cBTzOv
