defaultPortal: moon-site
portals:
  - name: moon-site
    portalId: 20072261
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLT46c6aLxIJAA0AAAAA4A0DGMWOyQkghKHcCyju6QwyGQCODAo2dUWJnYeoq6XTwYHu3oEKI0XsovQ6KAAABEEAAAB4AAAAAAAAAAAAAAAAAAAABAAAwAcA_v8xPAAABgAAAGBCGQCODAo2WgTk-ILmg3qHiszxNg_6owzmxrxKA25hMQ
        expiresAt: '2021-05-26T18:05:38.746Z'
    personalAccessKey: >-
      CiQ1YWI5MjE3ZC0yOTQ4LTQ5OTYtOWZjMi1jOTNhNmQ2YmU0ZjgQxY7JCRiEodwLKhkABeaRgsMOYTMgt4IqEpzJnYvzE-cBTzOv
